repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: '\.json$'
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx|svelte)$
        args: [--fix]
        additional_dependencies:
          - eslint
          - eslint-plugin-svelte
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
          - svelte-eslint-parser

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|svelte|json|css|scss|md|html)$
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
